### ISSUE TITLE
Do local checks before attempting upload

### ISSUE THREAD

**Issue by valadas** [valadas/Dnn.Platform#130]
Currently the upload control uses the API to determine if the extension is allowed and if the max file size is too large.
This works but with the drawback that the upload needs to complete before those things are checked which wastes resources.

Solution:
We need to provide this information to the frontend and do a local handling to not attempt the upload if we know it will ultimately be refused anyway.

**Comment by david-poindexter** [comment]
Okay, I think this one can be closed now.
