### ISSUE TITLE
I like to contribute to developing DNN.Platform

### ISSUE THREAD

**Issue by Mostafa-Moafi** [valadas/Dnn.Platform#151]
Hello, Mr.Valadas
I like to contribute to developing DNN.Platform
and saw your video about it.
Can you help me to select an issue and solve it?

I know that it would have been better to leave my message in another way, but I'm sorry, I couldn't find another way of communication.

And thank you very much to help me

**Comment by valadas** [comment]
We have a "Help Wanted" label you can try if you don't know what to pick
https://github.com/dnnsoftware/Dnn.Platform/labels/help%20wanted

Or you can go by the oldest issues to help clean the backlog

But overall it depends what you feel talented to tackle. It is a large codebase that uses a lot of different technologies, so it all depends on what you feel comfortable tackling.

**Comment by Mostafa-Moafi** [comment]
Thank you for help me.

You will see my pull requests soon
