### ISSUE TITLE
Update manifest to cleanup old js files

### ISSUE THREAD

**Issue by valadas** [valadas/Dnn.Platform#34]
The stencil build generates files names with a hash, this means we can't really differentiate the old from the new javascript files easily.

This is why I implemented globbing patterns supper for the manifest cleanup task. We need in this module to implement that as in https://docs.dnncommunity.org/content/tutorials/extensions/dnn-manifest-schema/index.html#components
(search for `glob` in there to get a clue of how that new feature works.

**Comment by valadas** [comment]
Probably should also cleanup view.ascx file

**Comment by david-poindexter** [comment]
You can assign this one to me.
